name: ClusterFuzzLite

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions: read-all


jobs:
  fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Override for this step to allow writing crash artifacts
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Fuzz Tests
        run: |
          go test -fuzz=. -fuzztime=60s

      - name: Upload Crash Artifacts
        if: failure()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: fuzz-crashers
          path: fuzz_crashers/
